apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: day40-ai-ci-app
spec:
  template:
    spec:
      containers:
        - image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
      timeoutSeconds: 300
