name: Day40 Main CI/CD Pipeline

on:
  push:
    branches: [ "Day40" ]
  workflow_dispatch:

env:
  REGION: asia-south1
  SERVICE_NAME: day40-ai-ci-app
  ARTIFACT_REPO: day40-docker-repo

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r Day40/app/requirements.txt
      - run: pip install pytest
      - run: pytest Day40/tests -q

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
      - run: docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/day40-docker-repo/day40-ai-ci-app ./Day40
      - run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/day40-docker-repo/day40-ai-ci-app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: day40-ai-ci-app
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/day40-docker-repo/day40-ai-ci-app
          region: asia-south1
